### ISSUE TITLE
META Element does not work properly

### ISSUE THREAD

**Issue by ITNEMKH** [i7MEDIA/mojoportal#112]
OS: Windows Server 2008

DB platform: SQLite

Version: 2.7.0.0

.NET Framework: 4.7, Integrated

After inserting a new article, the default values in Page Meta Data are set incorrectly - see below explicit HTML. Unable to update Meta Element, still returning to original bad value.

I'm not an ASP programmer, but I found a bug in the code mojo.Portal.Data.SQLite - mojoPortal.Data.DBContentMeta - Update:

string contentProerty.

On the same hosting where I have the MSSQLL DB Platform, everything is fine!

Explicit HTML:

<meta name="name" name="Roční příběh Barborky"  />

<meta description="description" description="Chrám sv. Barbory v Kutné Hoře Přejít na tento sway"  />

<meta image="image" image="https://foto.pechanec.cz/Data/Sites/1/media/barborka.jpg"  />

<meta og:type="og:type" og:type="article"  />

<meta og:site_name="og:site_name" og:site_name="Fotostránky Igorovo"  />

<meta og:title="og:title" og:title="Roční příběh Barborky"  />

<meta og:url="og:url" og:url="https://foto.pechanec.cz/pribeh-barborky"  />

<meta og:description="og:description" og:description="Chrám sv. Barbory v Kutné Hoře Přejít na tento sway"  />

<meta og:image="og:image" og:image="https://foto.pechanec.cz/Data/Sites/1/media/barborka.jpg"  />

<meta twitter:card="twitter:card" twitter:card="summary_large_image"  />

<meta twitter:title="twitter:title" twitter:title="Příběh Barborky"  />

<meta twitter:description="twitter:description" twitter:description="Chrám sv. Barbory v Kutné Hoře Přejít na tento sway"  />

<meta twitter:image="twitter:image" twitter:image="https://foto.pechanec.cz/Data/Sites/1/media/barborka.jpg"  />

**Comment by Alexeix** [comment]
This bug was catched on Version 2.8.0.7 MySQL
