### ISSUE TITLE
Better Image Gallery cannot handle dashes in name

### ISSUE THREAD

**Issue by joedavis01** [i7MEDIA/mojoportal#118]
Better image gallery really needs to be able to handle the dash in a filename.. (ex.  \images\item2-2021.jpg
  
currently the link is broken if there is a dash. What is a suggested fix that I can use to get this fixed for now.. 

also friendly folder names would be nice..

**Comment by JosephMDavis** [comment]
Can you send me to a page where this happens? It's working on the demo site.

**Comment by ElijahFowler** [comment]
Could not replicate.
