### ISSUE TITLE
Vulnerability in CSS Editor

### ISSUE THREAD

**Issue by JosephMDavis** [i7MEDIA/mojoportal#147]
We were recently made aware of a vulnerability in mojoPortal where the CssEditor in the "Design Tools" will allow someone with skin editing permissions (by default, only administrators) to see files located anywhere on the site, including the web.config.

### Work-Around
This is a little used feature so many people can use the following application setting to turn off editing, thus preventing this issue from causing them any harm. Simply add the following to your user.config and then restart your web application pool ([touch the web.config](https://www.mojoportal.com/touch-the-web-config)).
`<add key="AllowEditingSkins" value="false" />`

**Comment by lap1nou** [comment]
Good day,

I wanted to report additionnal information regarding this vulnerablity, but your "Report a vulnerability" forms doesn't work on your site, is there a way to contact you @JosephMDavis  ? Also your Twitter account no longer exist apparently.

**Comment by JosephMDavis** [comment]
Hi,

Thank you for letting us know about vulnerability report form, we'll get that fixed up. 

There are other contact forms on the site you can use. https://www.mojoportal.com/contact
