### ISSUE TITLE
Found CRITICAL Vulnerability in your website !

### ISSUE THREAD

**Issue by imchiragprajapati** [i7MEDIA/mojoportal#151]
Hello I am Chirag Prajapati a Certified Penetration Tester and Ethical Hacker my License no is: 10188-161-078-1726.

We would like to inform you that, a security vulnerability affecting your website.

Affected Website: mojoportal.com

Following the ISO/IEC 29147 (“Information technology — Security techniques — Vulnerability disclosure”) guidelines, we verified the vulnerability's existence prior to notifying you. Please connect with us for technical details of the vulnerability, 
The researcher may also help remediate the vulnerability if you need any assistance.

For more information I request you to kindly revert me back so that I can share with you the report !
Looking forward to hearing from you !

**Comment by JosephMDavis** [comment]
Hello,

I've responded to the email you sent us.

**Comment by JosephMDavis** [comment]
closed by commit b43f0b4

**Comment by imchiragprajapati** [comment]
Hello Sir,
Sorry to disturb your precious time.
If possible can I get some updates please ?
If you need anything else, please let me know.

I'll share that Information with you.

🙏

*Looking forward to hearing from you !*

**Comment by imchiragprajapati** [comment]
Hello Sir,
Sorry to disturb your precious time.
Whenever you are available.
If possible, can I get some updates for my opportunity please ?
🙏

Looking forward to hearing from you !
