### ISSUE TITLE
Found CRITICAL Vulnerability in your website !

### ISSUE THREAD

**Issue by imchiragprajapati** [i7MEDIA/mojoportal#152]
Hello @JosephMDavis Sir,
I have found another CRITICAL Vulnerability in your website.
Please revert me back on our previous mail thread Email: bugbounty.chirag@gmail.com

My Report is ready to send.

**Looking forward to hearing from you !**

**Comment by JosephMDavis** [comment]
We've been communicating by email. There is no need for this public post.
