### ISSUE TITLE
MemberList: Alphabetical filtering is displayed incorrectly

### ISSUE THREAD

**Issue by joeystombaugh** [i7MEDIA/mojoportal#168]
The text in the members page is in a straight column on the left side of the screen.

**Comment by joeystombaugh** [comment]
Example


![Image](https://user-images.githubusercontent.com/100313953/224442579-25af9786-5876-4325-b13b-45bdf5d9ce9b.png)

**Comment by JosephMDavis** [comment]
fixed by #b65d449
