### ISSUE TITLE
Author information consistency

### ISSUE THREAD

**Issue by joeystombaugh** [i7MEDIA/mojoportal#173]
user information under blog post list have a border and background, but do not under the blog features themselves

**Comment by joeystombaugh** [comment]
blog feature: 

![Image](https://user-images.githubusercontent.com/100313953/224442906-8de09faa-9e0a-4b38-ba95-4fda02232f4d.png)

blog post list feature:

![Image](https://user-images.githubusercontent.com/100313953/224442956-6939614b-3f17-4718-bef8-570449488fa7.png)

**Comment by Isaac-Hall** [comment]
This is fixed in a recent update to Framework. https://github.com/i7MEDIA/mojoskins/commit/91ed524f508945e58a492d004cc3c172146b442d
