### ISSUE TITLE
Poll meters should always be below option title

### ISSUE THREAD

**Issue by joeystombaugh** [i7MEDIA/mojoportal#176]
it would be nice if the poll bars were ALWAYS under the option instead of sometimes being next to it when the title is short [example](https://mtest-mssql.i7demo.com/Admin/ContentManagerPreview.aspx?mid=13)

**Comment by joeystombaugh** [comment]
![Image](https://user-images.githubusercontent.com/100313953/224443121-cc15d0a8-9721-4f93-b376-8d96c227b15e.png)

**Comment by Isaac-Hall** [comment]
This is fixed in a recent update to Framework. https://github.com/i7MEDIA/mojoskins/commit/91ed524f508945e58a492d004cc3c172146b442d
