### ISSUE TITLE
image thumbnails are very tiny when using better image gallery on a side bar

### ISSUE THREAD

**Issue by joeystombaugh** [i7MEDIA/mojoportal#180]
![Image](https://user-images.githubusercontent.com/100313953/224443493-c3e4ed64-ed1d-407e-89fa-46ec5d276e68.png)

**Comment by JosephMDavis** [comment]
This is a skinning issue. Creation of a new "view" for use in the sidebar may be necessary but it can probably be fixed with flexbox.

**Comment by Isaac-Hall** [comment]
Fixed in an update to Framework. https://github.com/i7MEDIA/mojoskins/commit/00b19ac4e283546c96f5333af6490e8424ef490b
