### ISSUE TITLE
Blog Entry Attachments: Large MP4 Upload Error

### ISSUE THREAD

**Issue by joseph-fowler** [i7MEDIA/mojoportal#186]
1. Edit blog entry. 
2. Under "Attachments" tab, link a large (~200MB) .MP4 file via "Choose Files" button and then click "Upload" 

The error "Oops something went wrong uploading, you may want to contact the site administrator an error was probably logged." is returned but no log entry is present in the system log. This issue is not present when uploading a smaller (~10MB) .MP4 file

**Comment by JosephMDavis** [comment]
This is resolved by following the directions in the "[Supporting Large File Uploads](https://www.mojoportal.com/docs/supporting-large-file-uploads)" article on the mojoPortal website. 

Currently, mojoPortal ships allowing file uploads for files smaller than 30mb. Should we change that to be higher?
