### ISSUE TITLE
Custom Menu Content: Crash

### ISSUE THREAD

**Issue by joseph-fowler** [i7MEDIA/mojoportal#190]
In Content Manager, add "Custom Menu" and click "Create New Content", site crashes

System log reports the following error: "System.Web.HttpParseException (0x80004005): Could not load type 'mojoPortal.Web.UI.CustomMenu'. ---> System.Web.HttpException (0x80004005): Could not load type 'mojoPortal.Web.UI.CustomMenu'"

**Comment by JosephMDavis** [comment]
fixed by [1eb1db3](https://github.com/i7MEDIA/mojoportal/commit/1eb1db3343e24b25e01e2b13e715dc81bd12ae88)
