### ISSUE TITLE
Superflexy issues

### ISSUE THREAD

**Issue by SinaBina** [i7MEDIA/mojoportal#213]
Hi
In the latest version the Superflexi module has some issues.To reproduce :

**Issue one:**
1-Install fresh site
2-Add Superflexi module to the homepage
3-hit module"Settings" and add "Slider/Banner"
4-hit "Settings" again and you are redirected to "access Denied" page:

The issue is related to the link.It is "**http://localhost:57394/Admin/ModuleSettings.aspx?pageid=0&mid=2**" while it should be "**http://localhost:57394/Admin/ModuleSettings.aspx?pageid=1&mid=2**"

**Issue two**
1-
2-Add Superflexi module to the homepage
3-hit module"Settings" and add "Slider/Banner"
4-Add couple of slides
5-back to main page and all slides appear below each other with no effect.

![Screenshot 2023-06-24 at 10-09-21 Home - mojoPortal](https://github.com/i7MEDIA/mojoportal/assets/5496007/2f8f14fa-dc01-46ee-8dc8-bcf60a57cafc)

Regards

**Comment by ElijahFowler** [comment]
Hi,

Thanks for the bug report. We have a fix for this already in place, it will be included in the upcoming 2.9.0.1 release.

**Comment by SinaBina** [comment]
Hi
Unfortunately the issue is still present in 2.9.0.1.

**Comment by JosephMDavis** [comment]
Which issue is still present? The Settings link issue should definitely be fixed. The second issue may be fixed by uploading a newer version of the skin you're using (it looks like Scout).

**Comment by SinaBina** [comment]
The second issue I mean.I just downloaded the latest source and tried with "Framework" skin with the same result.

**Comment by SinaBina** [comment]
Any solution?

**Comment by Isaac-Hall** [comment]
[Banner Slider.zip](https://github.com/i7MEDIA/mojoportal/files/12336232/Banner.Slider.zip)

I believe this solution should fix things. It may require that you edit the individual slides and make sure the data is in correctly because the field defs are different.

**Comment by SinaBina** [comment]
Tx. I will get back with result.

**Comment by SinaBina** [comment]
It is fixed.
