### ISSUE TITLE
Compilation error regarding ILog, Log4Net and CsvHelper

### ISSUE THREAD

**Issue by SinaBina** [i7MEDIA/mojoportal#228]
Hi
Clean rebuilding the latest source using VS2022 17.7.2 with no changes throws the following errors.Adding reference manually to the corresponding binaries located in packages folder (for NuGet) fix issues.

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Data.MSSQL	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Data.MSSQL\dbPortal.cs	30	Active
Error	CS0246	The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Data.MSSQL	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Data.MSSQL\SQLParameterHelper.cs	1	Active
Error	CS0246	The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Editor	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Editor\EditorControl.cs	16	Active
Error	CS0246	The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Editor	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Editor\TextArea\TextAreaEditorControl.cs	23	Active
Error	CS0246	The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Editor	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Editor\XStandard\XStandardControl.cs	24	Active
Error	CS0246	The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\Crypto\CryptoHelper.cs	16	Active
Error	CS0246	The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\Crypto\mojoEncryptionConfiguration.cs	11	Active
Error	CS0246	The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\DateTimeHelper.cs	21	Active
Error	CS0246	The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\ResourceHelper.cs	21	Active
Error	CS0246	The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\SecurityHelper.cs	13	Active
Error	CS0246	The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\ServicePinger.cs	7	Active
Error	CS0246	The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\WebUtils.cs	25	Active
Error	CS0246	The type or namespace name 'ILog' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Data.MSSQL	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Data.MSSQL\dbPortal.cs	42	Active
Error	CS0246	The type or namespace name 'ILog' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Data.MSSQL	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Data.MSSQL\SQLParameterHelper.cs	14	Active
Error	CS0246	The type or namespace name 'ILog' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Editor	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Editor\EditorControl.cs	24	Active
Error	CS0246	The type or namespace name 'ILog' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Editor	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Editor\XStandard\XStandardControl.cs	38	Active
Error	CS0246	The type or namespace name 'ILog' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\Crypto\CryptoHelper.cs	24	Active
Error	CS0246	The type or namespace name 'ILog' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\Crypto\mojoEncryptionConfiguration.cs	18	Active
Error	CS0246	The type or namespace name 'ILog' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\DateTimeHelper.cs	28	Active
Error	CS0246	The type or namespace name 'ILog' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\ResourceHelper.cs	28	Active
Error	CS0246	The type or namespace name 'ILog' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\SecurityHelper.cs	19	Active
Error	CS0246	The type or namespace name 'ILog' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\ServicePinger.cs	27	Active
Error	CS0246	The type or namespace name 'ILog' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\WebUtils.cs	35	Active
Error	CS0246	The type or namespace name 'CsvHelper' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\ExportHelper.cs	4	Active
Error	CS0246	The type or namespace name 'CsvHelper' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\ExportHelper.cs	5	Active
Error	CS0246	The type or namespace name 'CsvHelper' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\ImportHelper.cs	1	Active
Error	CS0246	The type or namespace name 'CsvHelper' could not be found (are you missing a using directive or an assembly reference?)	mojoPortal.Web.Framework	C:\Users\User\Desktop\mojoportal-master\mojoPortal.Web.Framework\ImportHelper.cs	2	Active
`

![Untitled](https://github.com/i7MEDIA/mojoportal/assets/5496007/db3a1be2-7069-44bf-9ed7-02678f1fcdd0)

**Comment by JosephMDavis** [comment]
Hi,

It is best not to reference those libraries directly. You should right-click the solution and select "Restore NuGet Packages", then build (not rebuild) in this order:

1. mojoPortal.Data.<whatever DB you're using>
2. mojoPortal.Business
3. mojoPortal.Web (this will build Features and SuperFlexi as well)

**Comment by SinaBina** [comment]
I see.Thanks
