### ISSUE TITLE
Mojoportal MySql 2901 version cause setup error Object cannot be cast from DBNull to other types.

### ISSUE THREAD

**Issue by Alexeix** [i7MEDIA/mojoportal#231]
I just download latest mysql version, after connection string setup I launch default page with this error:

Object cannot be cast from DBNull to other types.

**Comment by Alexeix** [comment]
![image](https://github.com/i7MEDIA/mojoportal/assets/12558580/eeb7427d-de06-4212-8a97-6fe9b0943fdd)

**Comment by JosephMDavis** [comment]
Hello @Alexeix,

Are you debugging mojo in Visual Studio? If so, this is expected and you should just continue through the couple of errors.
