### ISSUE TITLE
Report Security Bug Using Demo

### ISSUE THREAD

**Issue by graphyhiren** [i7MEDIA/mojoportal#240]
Hello Team,

Just wanted to know if the Demo is the latest version of Mojoportal and can be used to report security Vulnerability?

**Comment by graphyhiren** [comment]
any updates ?

**Comment by graphyhiren** [comment]
Sure,

Please let me know once the demo is update to latest version and i will reconfirm the vulnerability if it exists in latest version as well and will submit the vulnerability report. Due some issue i am not able to deploy the mojo in my local system so i have checked it on demo.

**Comment by graphyhiren** [comment]
Hello,

It seems there is some issue with submit vulnerability button. It is stuck on Please wait and nothing happens. Could you please check.

**Comment by JosephMDavis** [comment]
Sorry about that, looks like we're testing a new feature on the mojo site and it has an issue, please email the report to support (at) i7media.net

**Comment by graphyhiren** [comment]
Hello @JosephMDavis 

Just sent the email with the vulnerability details. Please let me know incase anything required form my end.

Thank you.

**Comment by graphyhiren** [comment]
Hello,

Just for the confirmation if you have received the vulnerability report and is being processed ?

**Comment by graphyhiren** [comment]
Hello @JosephMDavis 

Any updates on the report ? also could you please let me know if the vulnerability is applicable for CVE once the issue is resolved.
