### ISSUE TITLE
Deletion from JQueryFileUpload fails when delete anything below a file that has already been deleted

### ISSUE THREAD

**Issue by CrispinF** [i7MEDIA/mojoportal#4]
the problem arises in line 410 of this 
mojoportal/PrototypeWeb/Controls/jQueryFileUpload.cs
A click handler is added to each file in the list, using its index in the array. Once any file has been deleted, this index is incorrect for files below the deleted file.
Could the file name be used instead of the index?
Or could the file list be regenerated with its delete handlers after each deletion?
I should add... we are going to have to fix this anyway in a few days time, so if you cannot suggest the best solution before we get to it, we will post our results in due course.

**Comment by joeaudette** [comment]
I don't have time to look into this now so you will likely get to it before I do

that one in PrototypeWeb was an early prototype, if you come up with a fix make sure you use [the one that is part of mojoPortal](https://github.com/joeaudette/mojoportal/blob/master/Web/Controls/jQuery/jQueryFileUpload.cs)
