### ISSUE TITLE
Flickr Module not Working

### ISSUE THREAD

**Issue by daka1510** [i7MEDIA/mojoportal#61]
![image](https://cloud.githubusercontent.com/assets/16404496/26027023/eefb230c-3806-11e7-9df3-bdd0d92cda3d.png)

Maybe the Flickr API has changed causing the JS code of the module to break?!

**Comment by JosephMDavis** [comment]
Closing this issue as we have removed the Flickr Module. We may add a new Flickr module in the future. If someone else wants to build one, that would be great!
