### ISSUE TITLE
Mojo 2.5.0.0  menu hiding 

### ISSUE THREAD

**Issue by joedavis01** [i7MEDIA/mojoportal#66]
I have installed the latest Mojo release (2.5.0.0) and am having a terrible issue with the Framework admin menu not auto-hiding on a mobile device.  Once you click on the menu icon and select a menu item the container remains and you have to click hide menu at the bottom.  The biggest issue is it is not intuitive and on top of that it really makes navigating on a mobile device difficult. 

I wasn't sure if this should reside here or the skins project.

**Comment by joedavis01** [comment]
I've noticed that browsing the demo site on a mobile device,  the admin menu hides,  but will not show back up to log out.

**Comment by ElijahFowler** [comment]
The first post is a skins project feature request and we will look for a solution.

The second one was a z-indexing issue in the demo site's skin changer, and that has now been fixed.

If you would like to repost your first issue in the skins project I can close this issue here.

**Comment by joedavis01** [comment]
Doing it now
