### ISSUE TITLE
Recaptcha V2

### ISSUE THREAD

**Issue by joedavis01** [i7MEDIA/mojoportal#68]
Is there support for Recaptcha V2 in the latest release of Mojoportal?
I cannot seem to get it working..

**Comment by JosephMDavis** [comment]
Yep, Recaptcha 2 was added a couple of years ago. What kind of trouble are you having with it?

**Comment by joedavis01** [comment]
I am getting an invalid site key. I dont see the setting in the admin panel to update it.

**Comment by JosephMDavis** [comment]
It's in Administration > Site Settings > Security (tab) > Anti-SPAM (tab). Pay attention to the order of the fields. I think it's backwards in mojoPortal compared to the way reCaptcha lists them.

**Comment by joedavis01** [comment]
WORKED GREAT !!    
FYI,  I is backwards.. thanks. Looking forward to the next release..

**Comment by ElijahFowler** [comment]
I've reordered the input in commit c1328cc192a5043dde561a13d80f4c71c9298ded, it will be included in the next update.
