### ISSUE TITLE
SuperFlexi settings in Configuration Manager

### ISSUE THREAD

**Issue by coe-jeubanks** [i7MEDIA/mojoportal#71]
Hey guys, I found some issues with the SuperFlexi projects in configuration manager for MySQL. 

1. The MSSQL versions of the data layer should not be marked to build with the Debug - MySQL and Release - MySQL configurations. 
2. The MySQL version of the data layer should not be marked to build with the Debug and Release configurations.
2. The configurations in the MySQL versions are incorrectly set to Release and Debug, rather than the MySQL versions of those.

**Comment by JosephMDavis** [comment]
Hi Jamie,

Thank you for reporting this. We had a bit of trouble with it to be honest. We were seeing in our own configurations that these things weren't set as you see them but publishing was still giving us a hard time. We'll have to take another look.

**Comment by coe-jeubanks** [comment]
Sounds good. I'm not sure where those settings are stored. I did try bringing everything down from scratch again just to verify that it wasn't something I'd done when I added our own custom projects back into the solution.

**Comment by JosephMDavis** [comment]
Hi Jamie,

I believe we have fixed these issues. Let me know if you continue to experience problems with them.

Thanks,
Joe
