### ISSUE TITLE
Blog Title doesn't render if Use Post Titles as Page Heading is checked and no page heading control exists

### ISSUE THREAD

**Issue by Isaac-Hall** [i7MEDIA/mojoportal#81]
If you enable the "Use Post Titles as Page Heading" option in the blog settings, but don't include a page heading control in your layout.Master file, the blog titles will not render at all on the post view.

The documentation for this setting states that if the Page Heading is not a feature your skin utilizes, checking the setting will do nothing. We should either update this documentation to state that checking the setting in that case will hide the post titles, or make it so that the post title renders normally (not as a page heading) if the page heading is not used by the skin.

**Comment by JosephMDavis** [comment]
fixed by 7d78ef3b5acdd00b9a0d77afd6708e13f3901919
