### ISSUE TITLE
Image url shows 404 error when CombineCSS is false in user.config file

### ISSUE THREAD

**Issue by ssamarian** [i7MEDIA/mojoportal#88]
When I use <add key="CombineCSS" value="false" /> in my user.config file, image url in chrome developer tool change like this:
http://localhost:8050/Data/Sites/1/skins/Scout-charity/css/img/newsletter-bg.jpg
and image not found.
but when I use 
<add key="CombineCSS" value="true" />
url is like this:
http://localhost:8050/Data/Sites/1/skins/Scout/img/newsletter-bg.jpg

**Comment by JosephMDavis** [comment]
Hi Sadegh,

This is expected and is normal CSS behavior. Your file structure looks like this:

/data/sites/1/skins/Scout-charity/css/(css files)
/data/sites/1/skins/Scout-charity/img/(image files)

In your CSS files, you are referencing images like this:
url('img/image.png')
which tells the browser to find the image at /data/sites/1/skins/Scout-charity/css/img/image.png.

If you want the browser to find the image in a folder above the 'css' folder, you need to do this:
url('../img/image.png')

Doing this will work when the CombineCSS option is off (false) but it will not work when the CombineCSS option is on (true).

Turning off the CombineCSS option tells mojoPortal to do nothing with the file at all. No minification, no file path parsing, etc... Why do you need to turn this option off in the first place?

**Comment by ssamarian** [comment]
Hi Joe, thank you.
I need to turn combineCSS off for better understand that which class in the which file.
