### ISSUE TITLE
SuperFlexi Module links

### ISSUE THREAD

**Issue by joedavis01** [i7MEDIA/mojoportal#92]
I pulled a fresh copy of mojo 2.6.0.0 source, built the solution and ran against a new database. 
I logged in as admin, added a SuperFlexi module to a new page and using the settings link chose the banner solution then saved. 

Once the banner saved and refreshed the only module link available was **settings**.

I tried to clear the browser cache, reset the cache on the site, and even tried the solution posted [here](https://www.mojoportal.com/Forums/Thread.aspx?pageid=5&t=13741~1)

I took a look at the page markup ( shown below ) and it looks like the only module link generated is **settings**.  

```
<div class="modulecontent">           

<div id="module9" data-contentsection="Demo Super Flexi - Banner" class="content-slider">
<span class="content-slider__module-links modulelinks flexi-module-links">
<a class="ModuleEditLink flexi-settings" href="http://localhost:55906/Admin/ModuleSettings.aspx?pageid=2&amp;mid=9">
<i class="fa fa-cog"></i> Settings</a> &nbsp;</span>
<div class="content-slider__items slick-initialized slick-slider">
<div aria-live="polite" class="slick-list draggable">
<div class="slick-track" role="listbox" style="opacity: 1; width: 0px;">
</div>
</div>
</div>
<div class="content-slider__controls"></div>
</div>              
            
</div>
```
Any chance this is a bug or is there a fix I need to apply?

**Comment by ElijahFowler** [comment]
This isn't replicable anymore, we believe it was fixed in version 2.7 or was fixed in the BannerSlider solution.
